namespace: "$NAMESPACE"
smtpUser: "$SMTP_USER"
smtpPass: "$SMTP_PASS"
sender: "sns@alerts.zxc.com"
recipientList: "'asd@gmail.com','qwe@gmail.com'"
alert: 
microservice:
      - service: "nginx"
        port: 80
        context_path: "" #No need to add /abc 
        path: "/"
